language: c++
addons:
  apt:
    sources: &common_sources
      - sourceline: deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64 /
        key_url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/7fa2af80.pub
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages: &common_packages
      - cmake
      - ninja-build
      - libopencv-dev
      - libfftw3-dev
      - cuda-command-line-tools-8-0 cuda-cufft-dev-8-0 cuda-cublas-dev-8-0

env:
  - CUDA_BIN_PATH=/usr/local/cuda-8.0 CXXFLAGS=-Werror CUDA_ARCH_LIST=6.2 NINJA_STATUS="[%f/%t] "

script: make

matrix:
  include:
    - compiler: gcc-5
      addons:
        apt:
          sources: *common_sources
          packages:
            - *common_packages
            - g++-5
      script: make CC=gcc-5 CXX=g++-5
    - compiler: clang-3.8
      addons:
        apt:
          sources: *common_sources
          packages:
            - *common_packages
            - clang-3.8
      script: make CC=clang-3.8 CXX=clang++-3.8 $(grep -v openmp .kcf_builds)
    - compiler: clang
      name: clang & test
      script:
        - make BUILDS="$(echo $(grep -v cufft .kcf_builds))"
        - "ninja test || :"
      after_script: find vot2016 -name output.txt -o -name core -print0 | xargs -0 rm -f
      addons:
        apt: { sources: *common_sources, packages: [*common_packages, unzip] }

before_script:
    - make -qp|grep "^BUILDS ="|grep -o '[a-z-]*' | tee .kcf_builds

cache:
  directories: [ vot2016 ]
